default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost
  port: 5432

development:
  <<: *default
  database: awdwr_development

test:
  <<: *default
  database: awdwr_test

production:
  <<: *default
  database: awdwr_production
